/**
 * OshiPulse 初始資料庫種子與本機狀態儲存引擎 (DataService)
 * 支援雙軌實體架構 (Dual-Tier Entity Architecture: universe vs solo)
 * 支援無外部 Supabase 連線時的離線完整互動與持久化
 */
import {
  Idol,
  Member,
  EntityType,
  Battle,
  Collab,
  Product,
  ContactMessage,
  Profile,
  TimelineMilestone,
} from "./supabase/types";

export type { EntityType, Member, Idol };

export const INITIAL_IDOLS: Idol[] = [
  // ========================================================
  // 【韓國頂級動漫/條漫 IP - 純個人單人角色】
  // ========================================================
  {
    id: "char-sung-jinwoo",
    name: "成振宇 (Sung Jinwoo)",
    original_name: "성진우",
    country: "KR",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2018,
    avatar_url: "/images/idols/sung-jinwoo.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx105398-b673VtlCXHQT.jpg",
    wiki_slug: "Sung_Jinwoo",
    vote_count: 58200,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [{ name: "成振宇", gender: "male", birth_date: null, is_unrevealed: true, zodiac: "暗影君王 ✦", avatar_url: "/images/idols/sung-jinwoo.jpg" }],
    notable_works: [{ type: "代表作", title: "我獨自升級 (Solo Leveling)" }, { type: "神技", title: "起來 (Arise) / 闇影提取" }],
    official_links: [{ name: "Kakao Webtoon", url: "https://webtoon.kakao.com" }]
  },
  {
    id: "char-kim-dokja",
    name: "金獨子 (Kim Dokja)",
    original_name: "김독자",
    country: "KR",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2018,
    avatar_url: "/images/idols/kim-dokja.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/manga/cover/large/bx119257-2VOnp9aL30xG.png",
    wiki_slug: "Kim_Dokja",
    vote_count: 53100,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [{ name: "金獨子", gender: "male", birth_date: "1991-02-15", is_unrevealed: false, zodiac: "水瓶座 ♒︎", avatar_url: "/images/idols/kim-dokja.jpg" }],
    notable_works: [{ type: "代表作", title: "全知讀者視角" }, { type: "專屬星痕", title: "全知讀者視角 / 書籤" }],
    official_links: [{ name: "Naver Webtoon", url: "https://comic.naver.com" }]
  },

  // ========================================================
  // 【韓國 K-Pop 頂流偶像 - 個人單體拆分】
  // ========================================================
  {
    id: "idol-jungkook",
    name: "田柾國 (Jung Kook)",
    original_name: "전정국",
    country: "KR",
    category: "singer",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2013,
    avatar_url: "/images/idols/jungkook.jpg",
    cover_url: "https://upload.wikimedia.org/wikipedia/commons/4/4e/BTS_for_Dispatch_White_Day_Special%2C_27_February_2019_01.jpg",
    wiki_slug: "Jungkook",
    vote_count: 62500,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [{ name: "Jung Kook", gender: "male", birth_date: "1997-09-01", is_unrevealed: false, zodiac: "處女座 ♍︎", avatar_url: "/images/idols/jungkook.jpg" }],
    notable_works: [{ type: "Solo 神曲", title: "Seven (feat. Latto)" }],
    official_links: [{ name: "BIGHIT", url: "https://ibighit.com" }]
  },
  {
    id: "idol-wonyoung",
    name: "張員瑛 (Wonyoung)",
    original_name: "장원영",
    country: "KR",
    category: "singer",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2018,
    avatar_url: "/images/idols/wonyoung.jpg",
    cover_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/230811_Jamboree_K-Pop_Super_Live_IVE.jpg/1200px-230811_Jamboree_K-Pop_Super_Live_IVE.jpg",
    wiki_slug: "Jang_Won-young",
    vote_count: 59800,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [{ name: "張員瑛", gender: "female", birth_date: "2004-08-31", is_unrevealed: false, zodiac: "處女座 ♍︎", avatar_url: "/images/idols/wonyoung.jpg" }],
    notable_works: [{ type: "流行語", title: "Lucky Vicky 🍀" }, { type: "所屬團體", title: "IVE" }],
    official_links: [{ name: "Starship", url: "http://www.starship-ent.com" }]
  },

  // ========================================================
  // 【日本動漫角色 - 正確圖像修正】
  // ========================================================
  {
    id: "char-gojo",
    name: "五條悟",
    original_name: "五条 悟 (Satoru Gojo)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2018,
    avatar_url: "/images/idols/gojo-satoru.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pEFseh.jpg",
    wiki_slug: "Satoru_Gojo",
    vote_count: 65200,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [{ name: "五條悟", gender: "male", birth_date: "1989-12-07", is_unrevealed: false, zodiac: "射手座 ♐︎", avatar_url: "/images/idols/gojo-satoru.jpg" }],
    notable_works: [{ type: "領域展開", title: "無量空處" }],
    official_links: [{ name: "咒術迴戰官網", url: "https://jujutsukaisen.jp" }]
  },
  {
    id: "char-frieren",
    name: "芙莉蓮 (Frieren)",
    original_name: "フリーレン",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2020,
    avatar_url: "/images/idols/frieren.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154587-g1roJ6R7zJ6C.jpg",
    wiki_slug: "Frieren",
    vote_count: 54100,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [{ name: "芙莉蓮", gender: "female", birth_date: null, is_unrevealed: true, zodiac: "千年精靈 ✦", avatar_url: "/images/idols/frieren.jpg" }],
    notable_works: [{ type: "代表作", title: "葬送的芙莉蓮" }],
    official_links: [{ name: "動畫官方網站", url: "https://frieren-anime.jp" }]
  },

  {
    id: "idol-1",
    name: "星街彗星",
    original_name: "星街すいせい",
    country: "JP",
    category: "vtuber",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2018,
    avatar_url: "/images/idols/1.jpg",
    cover_url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200",
    wiki_slug: "Hoshimachi_Suisei",
    spotify_track_id: "7x92d7UoGqKsp14yM6lZcR",
    youtube_video_id: "a51VH9BYzZA",
    vote_count: 14205,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "星街すいせい",
        gender: "female",
        birth_date: null,
        is_unrevealed: true,
        zodiac: "未知星屑 ✦",
        avatar_url: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200",
      },
    ],
    notable_works: [
      { type: "歌曲", title: "Stellar Stellar" },
      { type: "歌曲", title: "ビビデバ" },
    ],
    official_links: [
      { name: "官方 X", url: "https://twitter.com/suisei_hosimati" },
      { name: "YouTube", url: "https://youtube.com/@HoshimachiSuisei" },
    ],
  },
  {
    id: "idol-2",
    name: "周杰倫",
    original_name: "Jay Chou",
    country: "TW",
    category: "singer",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2000,
    avatar_url: "/images/idols/2.jpg",
    cover_url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200",
    wiki_slug: "Jay_Chou",
    spotify_track_id: "2elA8uR2vWb7nS20x3YgUf",
    youtube_video_id: "mp0jFkYJc3c",
    vote_count: 13950,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "周杰倫",
        gender: "male",
        birth_date: "1979-01-18",
        is_unrevealed: false,
        zodiac: "摩羯座 ♑︎",
        avatar_url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=200",
      },
    ],
    notable_works: [
      { type: "代表作", title: "青花瓷" },
      { type: "電影", title: "不能說的秘密" },
    ],
    official_links: [{ name: "Instagram", url: "https://instagram.com/jaychou" }],
  },
  {
    id: "idol-3",
    name: "NewJeans",
    original_name: "뉴진스",
    country: "KR",
    category: "singer",
    entity_type: "universe",
    formation: "group",
    debut_year: 2022,
    avatar_url: "/images/idols/3.jpg",
    cover_url: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200",
    wiki_slug: "NewJeans",
    spotify_track_id: "65FftVqd5MW6u0bqrR0v4s",
    youtube_video_id: "js1Ctxc36AM",
    vote_count: 12890,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "Minji",
        gender: "female",
        birth_date: "2004-05-07",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "/images/idols/admin-user-id.jpg",
      },
      {
        name: "Hanni",
        gender: "female",
        birth_date: "2004-10-06",
        is_unrevealed: false,
        zodiac: "天秤座 ♎︎",
        avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200",
      },
      {
        name: "Danielle",
        gender: "female",
        birth_date: "2005-04-11",
        is_unrevealed: false,
        zodiac: "牡羊座 ♈︎",
        avatar_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200",
      },
      {
        name: "Haerin",
        gender: "female",
        birth_date: "2006-05-15",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
      },
      {
        name: "Hyein",
        gender: "female",
        birth_date: "2008-04-21",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=200",
      },
    ],
    notable_works: [
      { type: "歌曲", title: "Ditto" },
      { type: "歌曲", title: "Hype Boy" },
    ],
    official_links: [{ name: "官方 X", url: "https://twitter.com/NewJeans_ADOR" }],
  },
  {
    id: "idol-4",
    name: "泰勒絲",
    original_name: "Taylor Swift",
    country: "US",
    category: "singer",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2006,
    avatar_url: "/images/idols/4.jpg",
    cover_url: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200",
    wiki_slug: "Taylor_Swift",
    spotify_track_id: "06HL4z0CvFAxyc27GXpf02",
    youtube_video_id: "b1kbLwvqugk",
    vote_count: 12100,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "Taylor Swift",
        gender: "female",
        birth_date: "1989-12-13",
        is_unrevealed: false,
        zodiac: "射手座 ♐︎",
        avatar_url: "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7?w=200",
      },
    ],
    notable_works: [
      { type: "代表作", title: "Cruel Summer" },
      { type: "巡演", title: "The Eras Tour" },
    ],
    official_links: [{ name: "官方網站", url: "https://www.taylorswift.com" }],
  },
  {
    id: "idol-5",
    name: "花澤香菜",
    original_name: "Kana Hanazawa",
    country: "JP",
    category: "seiyuu",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2003,
    avatar_url: "/images/idols/5.jpg",
    cover_url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200",
    wiki_slug: "Kana_Hanazawa",
    spotify_track_id: "702KjI6CgP4W66k8uBv0xG",
    youtube_video_id: "k7m84Hn9s7k",
    vote_count: 9840,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "花澤香菜",
        gender: "female",
        birth_date: "1989-02-25",
        is_unrevealed: false,
        zodiac: "雙魚座 ♓︎",
        avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
      },
    ],
    notable_works: [
      { type: "角色配音", title: "千石撫子 (物語系列)" },
      { type: "代表歌曲", title: "戀愛循環" },
    ],
    official_links: [{ name: "官方 X", url: "https://twitter.com/hanazawa_staff" }],
  },
  {
    id: "idol-6",
    name: "肖戰",
    original_name: "Sean Xiao",
    country: "CN",
    category: "actor",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2015,
    avatar_url: "/images/idols/6.jpg",
    cover_url: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1200",
    wiki_slug: "Xiao_Zhan",
    spotify_track_id: "3rW7lOQ4U4yV5Nq9zC7G",
    youtube_video_id: "D13Yk0Tj3k8",
    vote_count: 9210,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "肖戰",
        gender: "male",
        birth_date: "1991-10-05",
        is_unrevealed: false,
        zodiac: "天秤座 ♎︎",
        avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
      },
    ],
    notable_works: [
      { type: "電視劇", title: "陳情令" },
      { type: "電視劇", title: "夢中的那片海" },
    ],
    official_links: [{ name: "微博工作室", url: "https://weibo.com" }],
  },
  {
    id: "idol-7",
    name: "統神",
    original_name: "Asiagodtone",
    country: "TW",
    category: "creator",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2013,
    avatar_url: "/images/idols/7.jpg",
    cover_url: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200",
    wiki_slug: "亞洲統神",
    spotify_track_id: null,
    youtube_video_id: "YQHsXMglC9A",
    vote_count: 8650,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "張嘉航",
        gender: "male",
        birth_date: "1988-09-12",
        is_unrevealed: false,
        zodiac: "處女座 ♍︎",
        avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200",
      },
    ],
    notable_works: [{ type: "知名實況", title: "英雄聯盟戰隊 HPS 創辦人" }],
    official_links: [{ name: "YouTube 頻道", url: "https://youtube.com" }],
  },
  {
    id: "idol-8",
    name: "AKB48",
    original_name: "AKB48",
    country: "JP",
    category: "singer",
    entity_type: "universe",
    formation: "group",
    debut_year: 2005,
    avatar_url: "/images/idols/8.jpg",
    cover_url: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200",
    wiki_slug: "AKB48",
    spotify_track_id: "51G2U1H6jP5x1Hj2P0",
    youtube_video_id: "lkHlnWFnJ4c",
    vote_count: 8340,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "小栗有以",
        gender: "female",
        birth_date: "2001-12-26",
        is_unrevealed: false,
        zodiac: "摩羯座 ♑︎",
        avatar_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=200",
      },
      {
        name: "倉野尾成美",
        gender: "female",
        birth_date: "2000-11-08",
        is_unrevealed: false,
        zodiac: "天蠍座 ♏︎",
        avatar_url: "/images/idols/admin-user-id.jpg",
      },
    ],
    notable_works: [
      { type: "代表作", title: "戀愛的幸運餅乾" },
      { type: "代表作", title: "Heavy Rotation" },
    ],
    official_links: [{ name: "官方網站", url: "https://www.akb48.co.jp" }],
  },
  {
    id: "idol-9",
    name: "IShowSpeed",
    original_name: "Darren Watkins Jr.",
    country: "US",
    category: "creator",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2016,
    avatar_url: "/images/idols/9.jpg",
    cover_url: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200",
    wiki_slug: "IShowSpeed",
    spotify_track_id: null,
    youtube_video_id: "mKkJyqYv3b8",
    vote_count: 7890,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "Darren Watkins Jr.",
        gender: "male",
        birth_date: "2005-01-21",
        is_unrevealed: false,
        zodiac: "水瓶座 ♒︎",
        avatar_url: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200",
      },
    ],
    notable_works: [{ type: "代表成就", title: "全球人氣 IRL 實況主" }],
    official_links: [{ name: "YouTube", url: "https://youtube.com/@IShowSpeed" }],
  },
  {
    id: "idol-10",
    name: "金秀賢",
    original_name: "Kim Soo-hyun",
    country: "KR",
    category: "actor",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2007,
    avatar_url: "/images/idols/10.jpg",
    cover_url: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200",
    wiki_slug: "Kim_Soo-hyun",
    spotify_track_id: null,
    youtube_video_id: "Gk8b1fG1e4w",
    vote_count: 7450,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "金秀賢",
        gender: "male",
        birth_date: "1988-02-16",
        is_unrevealed: false,
        zodiac: "水瓶座 ♒︎",
        avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
      },
    ],
    notable_works: [
      { type: "電視劇", title: "淚之女王" },
      { type: "電視劇", title: "來自星星的你" },
    ],
    official_links: [{ name: "Instagram", url: "https://instagram.com/soohyun_k216" }],
  },
  // ====================================================================
  // 【多媒體遊戲/企劃偶像 2.5D Franchise Idols】
  // ====================================================================
  {
    id: "idol-11",
    name: "Buster Bros!!!",
    original_name: "バスター ブロス",
    country: "JP",
    category: "singer",
    entity_type: "universe",
    formation: "group",
    debut_year: 2017,
    avatar_url: "/images/idols/11.jpg",
    cover_url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200",
    wiki_slug: "Hypnosis_Mic:_Division_Rap_Battle",
    spotify_track_id: "7x92d7UoGqKsp14yM6lZcR",
    youtube_video_id: "a51VH9BYzZA",
    vote_count: 23400,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "山田一郎 (MC.B.B)",
        gender: "male",
        birth_date: "1997-07-26",
        is_unrevealed: false,
        zodiac: "獅子座 ♌︎",
        avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
      },
      {
        name: "山田二郎 (MC.M.B)",
        gender: "male",
        birth_date: "1999-02-06",
        is_unrevealed: false,
        zodiac: "水瓶座 ♒︎",
        avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
      },
      {
        name: "山田三郎 (MC.L.B)",
        gender: "male",
        birth_date: "2001-12-16",
        is_unrevealed: false,
        zodiac: "射手座 ♐︎",
        avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200",
      },
    ],
    notable_works: [
      { type: "代表歌曲", title: "俺が一郎" },
      { type: "單曲", title: "IKEBUKURO WEST GAME PARK" },
    ],
    official_links: [{ name: "官方企劃網站", url: "https://hypnosismic.com" }],
  },
  {
    id: "idol-12",
    name: "MAD TRIGGER CREW",
    original_name: "マッド トリガー クルー",
    country: "JP",
    category: "singer",
    entity_type: "universe",
    formation: "group",
    debut_year: 2017,
    avatar_url: "/images/idols/6.jpg",
    cover_url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200",
    wiki_slug: "Hypnosis_Mic:_Division_Rap_Battle",
    spotify_track_id: "2elA8uR2vWb7nS20x3YgUf",
    youtube_video_id: "mp0jFkYJc3c",
    vote_count: 22900,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "碧棺左馬刻 (Mr.Hc)",
        gender: "male",
        birth_date: "1994-11-11",
        is_unrevealed: false,
        zodiac: "天蠍座 ♏︎",
        avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
      },
      {
        name: "入間銃兔 (45 Rabbit)",
        gender: "male",
        birth_date: "1991-05-30",
        is_unrevealed: false,
        zodiac: "雙子座 ♊︎",
        avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
      },
      {
        name: "毒島Mason理鶯 (Crazy M)",
        gender: "male",
        birth_date: "1989-06-21",
        is_unrevealed: false,
        zodiac: "雙子座 ♊︎",
        avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200",
      },
    ],
    notable_works: [
      { type: "代表歌曲", title: "Yokohama Walker" },
      { type: "單曲", title: "Scarface" },
    ],
    official_links: [{ name: "官方網站", url: "https://hypnosismic.com" }],
  },
  {
    id: "idol-13",
    name: "Fling Posse",
    original_name: "フリング ポッセ",
    country: "JP",
    category: "singer",
    entity_type: "universe",
    formation: "group",
    debut_year: 2017,
    avatar_url: "/images/idols/13.jpg",
    cover_url: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1200",
    wiki_slug: "Hypnosis_Mic:_Division_Rap_Battle",
    spotify_track_id: "65FftVqd5MW6u0bqrR0v4s",
    youtube_video_id: "js1Ctxc36AM",
    vote_count: 24100,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "飴村亂數 (easy R)",
        gender: "male",
        birth_date: "1996-02-14",
        is_unrevealed: false,
        zodiac: "水瓶座 ♒︎",
        avatar_url: "/images/idols/admin-user-id.jpg",
      },
      {
        name: "夢野幻太郎 (Phantom)",
        gender: "male",
        birth_date: "1996-04-01",
        is_unrevealed: false,
        zodiac: "牡羊座 ♈︎",
        avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200",
      },
      {
        name: "有栖川帝統 (Dead or Alive)",
        gender: "male",
        birth_date: "1997-07-07",
        is_unrevealed: false,
        zodiac: "巨蟹座 ♋︎",
        avatar_url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=200",
      },
    ],
    notable_works: [
      { type: "代表作", title: "Stella" },
      { type: "奪冠曲", title: "Shibuya Marble Texture" },
    ],
    official_links: [{ name: "官方網站", url: "https://hypnosismic.com" }],
  },
  {
    id: "idol-14",
    name: "ST☆RISH",
    original_name: "スターリッシュ",
    country: "JP",
    category: "singer",
    entity_type: "universe",
    formation: "group",
    debut_year: 2010,
    avatar_url: "/images/idols/14.jpg",
    cover_url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200",
    wiki_slug: "Uta_no_Prince-sama",
    spotify_track_id: "1x2y3z4w5v6u7t8s9r0q1p",
    youtube_video_id: "vR6M8_bK2w9",
    vote_count: 28500,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "一十木音也",
        gender: "male",
        birth_date: "1995-04-11",
        is_unrevealed: false,
        zodiac: "牡羊座 ♈︎",
        avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
      },
      {
        name: "聖川真斗",
        gender: "male",
        birth_date: "1994-12-29",
        is_unrevealed: false,
        zodiac: "摩羯座 ♑︎",
        avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
      },
      {
        name: "四之宮那月",
        gender: "male",
        birth_date: "1994-06-09",
        is_unrevealed: false,
        zodiac: "雙子座 ♊︎",
        avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200",
      },
      {
        name: "一之瀨時矢",
        gender: "male",
        birth_date: "1994-08-06",
        is_unrevealed: false,
        zodiac: "獅子座 ♌︎",
        avatar_url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=200",
      },
      {
        name: "神宮寺蓮",
        gender: "male",
        birth_date: "1993-02-14",
        is_unrevealed: false,
        zodiac: "水瓶座 ♒︎",
        avatar_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=200",
      },
      {
        name: "來栖翔",
        gender: "male",
        birth_date: "1995-06-09",
        is_unrevealed: false,
        zodiac: "雙子座 ♊︎",
        avatar_url: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200",
      },
      {
        name: "愛島賽西爾",
        gender: "male",
        birth_date: "1996-10-31",
        is_unrevealed: false,
        zodiac: "天蠍座 ♏︎",
        avatar_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200",
      },
    ],
    notable_works: [
      { type: "神曲", title: "真愛1000% (マジLOVE1000%)" },
      { type: "單曲", title: "真愛2000%" },
    ],
    official_links: [{ name: "官方企劃網站", url: "https://www.utapri.com" }],
  },
  {
    id: "idol-15",
    name: "QUARTET NIGHT",
    original_name: "カルテットナイト",
    country: "JP",
    category: "singer",
    entity_type: "universe",
    formation: "group",
    debut_year: 2012,
    avatar_url: "/images/idols/15.jpg",
    cover_url: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200",
    wiki_slug: "Uta_no_Prince-sama",
    spotify_track_id: "702KjI6CgP4W66k8uBv0xG",
    youtube_video_id: "k7m84Hn9s7k",
    vote_count: 25600,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "壽嶺二",
        gender: "male",
        birth_date: "1990-07-13",
        is_unrevealed: false,
        zodiac: "巨蟹座 ♋︎",
        avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
      },
      {
        name: "黑崎蘭丸",
        gender: "male",
        birth_date: "1991-09-29",
        is_unrevealed: false,
        zodiac: "天秤座 ♎︎",
        avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
      },
      {
        name: "美風藍",
        gender: "male",
        birth_date: "1998-03-01",
        is_unrevealed: false,
        zodiac: "雙魚座 ♓︎",
        avatar_url: "/images/idols/admin-user-id.jpg",
      },
      {
        name: "卡繆 (Camus)",
        gender: "male",
        birth_date: "1992-01-23",
        is_unrevealed: false,
        zodiac: "水瓶座 ♒︎",
        avatar_url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=200",
      },
    ],
    notable_works: [
      { type: "單曲", title: "Evolution Eve" },
      { type: "代表曲", title: "FLY TO THE FUTURE" },
    ],
    official_links: [{ name: "官方網站", url: "https://www.utapri.com" }],
  },
  {
    id: "idol-16",
    name: "A3! 滿開劇團 春組",
    original_name: "MANKAI Company Spring Troupe",
    country: "JP",
    category: "actor",
    entity_type: "universe",
    formation: "group",
    debut_year: 2017,
    avatar_url: "/images/idols/8.jpg",
    cover_url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200",
    wiki_slug: "A3!",
    spotify_track_id: "3rW7lOQ4U4yV5Nq9zC7G",
    youtube_video_id: "D13Yk0Tj3k8",
    vote_count: 19800,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "佐久間咲也",
        gender: "male",
        birth_date: "2000-03-09",
        is_unrevealed: false,
        zodiac: "雙魚座 ♓︎",
        avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
      },
      {
        name: "碓冰真澄",
        gender: "male",
        birth_date: "2001-01-17",
        is_unrevealed: false,
        zodiac: "摩羯座 ♑︎",
        avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
      },
      {
        name: "皆木綴",
        gender: "male",
        birth_date: "1999-04-09",
        is_unrevealed: false,
        zodiac: "牡羊座 ♈︎",
        avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200",
      },
      {
        name: "茅崎至",
        gender: "male",
        birth_date: "1996-04-24",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=200",
      },
      {
        name: "シトロン (Citron)",
        gender: "male",
        birth_date: "1997-05-15",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=200",
      },
      {
        name: "卯木千景",
        gender: "male",
        birth_date: "1994-04-15",
        is_unrevealed: false,
        zodiac: "牡羊座 ♈︎",
        avatar_url: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200",
      },
    ],
    notable_works: [
      { type: "公演劇目", title: "羅密歐與朱利葉斯" },
      { type: "主題曲", title: "春ですね。" },
    ],
    official_links: [{ name: "官方網站", url: "https://www.a3-liber.jp" }],
  },
  {
    id: "idol-17",
    name: "Knights",
    original_name: "ナイツ",
    country: "JP",
    category: "singer",
    entity_type: "universe",
    formation: "group",
    debut_year: 2015,
    avatar_url: "/images/idols/3.jpg",
    cover_url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200",
    wiki_slug: "Ensemble_Stars!",
    spotify_track_id: "6qqNVTkY8uBg9cP3Jd7DAH",
    youtube_video_id: "viimfQi_pfg",
    vote_count: 27600,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "月永雷歐 (月永レオ)",
        gender: "male",
        birth_date: "1998-05-05",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
      },
      {
        name: "瀨名泉",
        gender: "male",
        birth_date: "1998-11-02",
        is_unrevealed: false,
        zodiac: "天蠍座 ♏︎",
        avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
      },
      {
        name: "朔間凜月",
        gender: "male",
        birth_date: "1998-09-22",
        is_unrevealed: false,
        zodiac: "處女座 ♍︎",
        avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200",
      },
      {
        name: "鳴上嵐",
        gender: "female",
        birth_date: "1998-03-03",
        is_unrevealed: false,
        zodiac: "雙魚座 ♓︎",
        avatar_url: "/images/idols/admin-user-id.jpg",
      },
      {
        name: "朱櫻司",
        gender: "male",
        birth_date: "1999-04-06",
        is_unrevealed: false,
        zodiac: "牡羊座 ♈︎",
        avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200",
      },
    ],
    notable_works: [
      { type: "神曲", title: "Silent Oath" },
      { type: "代表作", title: "Voice of Sword" },
    ],
    official_links: [{ name: "官方網站", url: "https://ensemble-stars.jp" }],
  },
  // ====================================================================
  // 【頂級熱門動漫角色 Anime Characters (Solo)】
  // ====================================================================
  {
    id: "idol-21",
    name: "星野愛",
    original_name: "星野アイ (Hoshino Ai)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2020,
    avatar_url: "/images/idols/21.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx150672-NptLiy7e9wZl.jpg",
    wiki_slug: "Ai_Hoshino",
    spotify_track_id: "6WBI5crZrD9aR6aT4",
    youtube_video_id: "mAKsZ26SabQ",
    vote_count: 39500,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "星野愛",
        gender: "female",
        birth_date: "2003-05-07",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200",
      },
    ],
    notable_works: [
      { type: "所屬偶像團體", title: "B小町 (初代 C位)" },
      { type: "代表神曲", title: "我推的偶像 (アイドル)" },
    ],
    official_links: [{ name: "官方網站", url: "https://ichigoproduction.com" }],
  },
  {
    id: "idol-22",
    name: "里維·阿卡曼",
    original_name: "リヴァイ・アッカーマン",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2009,
    avatar_url: "/images/idols/22.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-73IhOXpJZiDY.png",
    wiki_slug: "Levi_Ackerman",
    spotify_track_id: null,
    youtube_video_id: "gdZLi9oWNZg",
    vote_count: 35400,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "里維·阿卡曼",
        gender: "male",
        birth_date: "1988-12-25",
        is_unrevealed: false,
        zodiac: "摩羯座 ♑︎",
        avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
      },
    ],
    notable_works: [
      { type: "稱號", title: "人類最強的士兵" },
      { type: "所屬", title: "調查兵團 特別作戰班 兵長" },
    ],
    official_links: [{ name: "進擊的巨人官方", url: "https://shingeki.tv" }],
  },
  // ====================================================================
  // 【超人氣聲優女子偶像 =LOVE (Equal Love)】
  // ====================================================================
  {
    id: "idol-23",
    name: "=LOVE",
    original_name: "イコールラブ (Equal Love)",
    country: "JP",
    category: "singer",
    entity_type: "universe",
    formation: "group",
    debut_year: 2017,
    avatar_url: "/images/idols/3.jpg",
    cover_url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200",
    wiki_slug: "=LOVE",
    spotify_track_id: "5tWpS8zP7nK6x1Y",
    youtube_video_id: "3kM1A9nF5pQ",
    vote_count: 26800,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "佐佐木舞香 (佐々木舞香)",
        gender: "female",
        birth_date: "2000-01-21",
        is_unrevealed: false,
        zodiac: "水瓶座 ♒︎",
        avatar_url: "/images/idols/admin-user-id.jpg",
      },

      {
        name: "野口衣織",
        gender: "female",
        birth_date: "2000-04-26",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200",
      },
      {
        name: "諸橋沙夏",
        gender: "female",
        birth_date: "1996-08-03",
        is_unrevealed: false,
        zodiac: "獅子座 ♌︎",
        avatar_url: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200",
      },
      {
        name: "大谷映美里",
        gender: "female",
        birth_date: "1998-03-15",
        is_unrevealed: false,
        zodiac: "雙魚座 ♓︎",
        avatar_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
      },
      {
        name: "音嶋莉沙",
        gender: "female",
        birth_date: "1998-08-11",
        is_unrevealed: false,
        zodiac: "獅子座 ♌︎",
        avatar_url: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=200",
      },
      {
        name: "齋藤樹愛羅",
        gender: "female",
        birth_date: "2004-11-26",
        is_unrevealed: false,
        zodiac: "射手座 ♐︎",
        avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200",
      },
    ],
    notable_works: [
      { type: "代表神曲", title: "あの子コンプレックス" },
      { type: "單曲", title: "=LOVE" },
      { type: "代表作", title: "絕對偶像辭典 (絶対アイドル辞めないで)" },
    ],
    official_links: [
      { name: "官方網站", url: "https://equal-love.jp" },
      { name: "官方 X", url: "https://twitter.com/Equal_LOVE_12" },
    ],
    timeline: [
      { year: "2017年", title: "指原莉乃海選誕生", desc: "代代木動畫學院協同打造，發行出道單曲《=LOVE》。" },
      { year: "2021年", title: "登上日本武道館", desc: "首度舉辦專場武道館演唱會，全場粉紅螢光棒震撼洗版。" },
      { year: "2022年", title: "神曲〈あの子コンプレックス〉", desc: "佐佐木舞香首次單獨擔任 C 位，串流突破數千萬次播放。" },
      { year: "2024年", title: "〈絕對偶像辭典〉現象級爆紅", desc: "成為全日本同名應援流行曲，聲優偶像界公認最高殿堂。" },
    ],
  },
  // ========================================================
  // 【=LOVE (等愛) 人氣單人成員 (entity_type: 'solo')】
  // ========================================================
  {
    id: "char-sasaki-maika",
    name: "佐佐木舞香",
    original_name: "佐々木舞香 (Sasaki Maika)",
    country: "JP",
    category: "singer",
    entity_type: "solo",
    universe_id: "idol-23",
    formation: "solo",
    debut_year: 2017,
    avatar_url: "/images/idols/3.jpg",
    cover_url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200",
    wiki_slug: "Maika_Sasaki",
    vote_count: 32400,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "佐佐木舞香",
        gender: "female",
        birth_date: "2000-01-21",
        is_unrevealed: false,
        zodiac: "水瓶座 ♒︎",
        avatar_url: "/images/idols/admin-user-id.jpg",
      },
    ],
    notable_works: [
      { type: "擔任 C 位神曲", title: "あの子コンプレックス" },
      { type: "代表作", title: "絕對偶像辭典 (絶対アイドル辞めないで)" },
    ],
    official_links: [
      { name: "佐佐木舞香 X (Twitter)", url: "https://twitter.com/sasaki_maika" },
      { name: "=LOVE 官網個人頁", url: "https://equal-love.jp" },
    ],
    timeline: [
      { year: "2017年", title: "以 =LOVE 一期生出道", desc: "憑藉極具穿透力的澄澈歌喉與出眾美貌引發巨大關注。" },
      { year: "2022年", title: "首次單獨 C 位〈あの子コンプレックス〉", desc: "悲戀神曲席捲串流，被譽為新世代聲優女團第一歌姬。" },
      { year: "2026年", title: "OshiPulse 個人角色榜高位", desc: "以超高個人應援凝聚力角逐偶像頂點！" }
    ]
  },
  {
    id: "char-noguchi-iori",
    name: "野口衣織",
    original_name: "野口衣織 (Noguchi Iori)",
    country: "JP",
    category: "singer",
    entity_type: "solo",
    universe_id: "idol-23",
    formation: "solo",
    debut_year: 2017,
    avatar_url: "/images/idols/15.jpg",
    cover_url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200",
    wiki_slug: "Iori_Noguchi",
    vote_count: 29800,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "野口衣織",
        gender: "female",
        birth_date: "2000-04-26",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200",
      },
    ],
    notable_works: [
      { type: "擔任 C 位神曲", title: "君と私の歌 (你與我的歌)" },
      { type: "代表作", title: "拜託了！魔法 (拝啓、貴方様へ)" },
    ],
    official_links: [
      { name: "野口衣織 X (Twitter)", url: "https://twitter.com/noguchi_iori" },
      { name: "=LOVE 官網個人頁", url: "https://equal-love.jp" },
    ]
  },

  // ========================================================
  // 【哆啦A夢 Doraemon - 純個人單人角色】
  // ========================================================
  {
    id: "char-doraemon",
    name: "哆啦A夢",
    original_name: "ドラえもん (Doraemon)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1969,
    avatar_url: "/images/idols/doraemon.jpg",
    cover_url: "https://upload.wikimedia.org/wikipedia/en/2/25/Doraemon_2005_anime_logo.png",
    wiki_slug: "Doraemon_(character)",
    vote_count: 56800,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "哆啦A夢",
        gender: "male",
        birth_date: "2112-09-03",
        is_unrevealed: false,
        zodiac: "處女座 ♍︎",
        avatar_url: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=200",
      },
    ],
    notable_works: [
      { type: "萬能法寶", title: "任意門、時光機、竹蜻蜓" },
      { type: "食物", title: "銅鑼燒" },
    ],
    official_links: [{ name: "哆啦A夢官網", url: "https://dora-world.com" }],
    timeline: [
      { year: "2112年", title: "貓型機器人誕生", desc: "誕生於松芝工廠，隨後搭乘時光機前往 20 世紀守護野比大雄。" },
      { year: "1969年", title: "藤子·F·不二雄連載展開", desc: "自小學館月刊展開連載，四次元口袋與任意門風靡全球。" },
      { year: "1980年", title: "首部大長篇《大雄的恐龍》", desc: "正式開啟年度春季電影黃金傳統，感動數世代觀眾。" },
      { year: "2014年", title: "《STAND BY ME 哆啦A夢》", desc: "首部 3D CG 電影創下全球票房紀錄，淚別大雄之經典重現。" },
    ],
  },
  {
    id: "char-nobita",
    name: "野比大雄",
    original_name: "野比 のび太 (Nobita Nobi)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1969,
    avatar_url: "/images/idols/nobita.jpg",
    cover_url: "https://upload.wikimedia.org/wikipedia/en/2/25/Doraemon_2005_anime_logo.png",
    wiki_slug: "Nobita_Nobi",
    vote_count: 48300,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "野比大雄",
        gender: "male",
        birth_date: "1964-08-07",
        is_unrevealed: false,
        zodiac: "獅子座 ♌︎",
        avatar_url: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=200",
      },
    ],
    notable_works: [{ type: "神技", title: "神槍手 (百發百中)、翻花繩天才" }],
    official_links: [{ name: "哆啦A夢官網", url: "https://dora-world.com" }],
  },
  {
    id: "char-gian",
    name: "剛田武 (胖虎)",
    original_name: "剛田 武 (Takeshi Goda)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1969,
    avatar_url: "/images/idols/gian.jpg",
    cover_url: "https://upload.wikimedia.org/wikipedia/en/2/25/Doraemon_2005_anime_logo.png",
    wiki_slug: "Takeshi_Goda",
    vote_count: 47900,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "胖虎",
        gender: "male",
        birth_date: "1964-06-15",
        is_unrevealed: false,
        zodiac: "雙子座 ♊︎",
        avatar_url: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=200",
      },
    ],
    notable_works: [
      { type: "靈魂招牌", title: "空地獨唱演唱會 (我是胖虎，我是孩子王～)" },
    ],
    official_links: [{ name: "哆啦A夢官網", url: "https://dora-world.com" }],
  },

  // ========================================================
  // 【咒術迴戰 - 純個人單人角色】
  // ========================================================
  {
    id: "char-sukuna",
    name: "兩面宿儺",
    original_name: "両面宿儺 (Ryomen Sukuna)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2018,
    avatar_url: "/images/idols/sukuna.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pEFseh.jpg",
    vote_count: 54100,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "兩面宿儺",
        gender: "male",
        birth_date: null,
        is_unrevealed: true,
        zodiac: "史上最強詛咒之王 ✦",
        avatar_url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=200",
      },
    ],
    notable_works: [{ type: "領域展開", title: "伏魔御廚子 (世界解)" }],
    official_links: [{ name: "咒術迴戰官網", url: "https://jujutsukaisen.jp" }],
    timeline: [
      { year: "千年前", title: "平安時代詛咒之巔", desc: "咒術全盛時代以一人之力擊潰眾多術師，死後二十根手指化為特級咒物。" },
      { year: "2018年", title: "虎杖悠仁吞食受肉甦醒", desc: "時隔千年降臨現代，於澀谷事變屠戮特級咒靈與魔虛羅。" },
      { year: "現代決戰", title: "伏魔御廚子完全解構", desc: "奪取伏黑惠肉身進化完全體，以世界解劃開新宿決戰終局。" },
    ],
  },
  {
    id: "char-fushiguro",
    name: "伏黑惠",
    original_name: "伏黒 恵 (Megumi Fushiguro)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2018,
    avatar_url: "/images/idols/fushiguro.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pEFseh.jpg",
    wiki_slug: "Megumi_Fushiguro",
    vote_count: 46200,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "伏黑惠",
        gender: "male",
        birth_date: "2002-12-22",
        is_unrevealed: false,
        zodiac: "摩羯座 ♑︎",
        avatar_url: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=200",
      },
    ],
    notable_works: [
      { type: "式神奧義", title: "十種影法術 (八握劍異戒神將魔虛羅)" },
    ],
    official_links: [{ name: "咒術迴戰官網", url: "https://jujutsukaisen.jp" }],
  },

  // ========================================================
  // 【全職獵人 HUNTER×HUNTER - 純個人單人角色】
  // ========================================================
  {
    id: "char-killua",
    name: "奇犽·揍敵客",
    original_name: "キルア＝ゾルディック (Killua)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1998,
    avatar_url: "/images/idols/killua.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-n5b7E2m8A24b.jpg",
    vote_count: 51200,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "奇犽",
        gender: "male",
        birth_date: "1987-07-07",
        is_unrevealed: false,
        zodiac: "巨蟹座 ♋︎",
        avatar_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=200",
      },
    ],
    notable_works: [{ type: "念能力", title: "變化系：神速 (疾風迅雷/電光石火)" }],
    official_links: [{ name: "少年JUMP官網", url: "https://www.shonenjump.com" }],
    timeline: [
      { year: "1998年", title: "第 287 期獵人試驗", desc: "逃離枯枯戮山殺手世家，在試驗中結識一生摯友小傑·富力士。" },
      { year: "友克鑫篇", title: "暗夜跟蹤幻影旅團", desc: "以超凡殺手步法穿梭於拍賣會死鬥，展示絕頂暗殺天賦。" },
      { year: "嵌合蟻篇", title: "拔除念針領悟「神速」", desc: "突破兄長伊耳謎的精神桎梏，以疾風迅雷電光石火超越音速！" },
    ],
  },
  {
    id: "char-gon",
    name: "小傑·富力士",
    original_name: "ゴン＝フリークス (Gon Freecss)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1998,
    avatar_url: "/images/idols/gon.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-n5b7E2m8A24b.jpg",
    vote_count: 49800,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "小傑",
        gender: "male",
        birth_date: "1987-05-05",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=200",
      },
    ],
    notable_works: [
      { type: "念能力", title: "猜猜拳 (石頭、剪刀、布) / 強制成長誓約" },
    ],
    official_links: [{ name: "少年JUMP官網", url: "https://www.shonenjump.com" }],
  },
  {
    id: "char-chrollo",
    name: "庫洛洛·魯西魯",
    original_name: "クロロ＝ルシルフル (Chrollo Lucilfer)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1998,
    avatar_url: "/images/idols/chrollo.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-n5b7E2m8A24b.jpg",
    vote_count: 48600,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "庫洛洛",
        gender: "male",
        birth_date: null,
        is_unrevealed: true,
        zodiac: "幻影旅團團長 ✦",
        avatar_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=200",
      },
    ],
    notable_works: [
      { type: "念能力", title: "特質系：盜賊的極意 (Skill Hunter)" },
      { type: "巔峰死鬥", title: "庫洛洛 vs 西索 天空競技場決戰" },
    ],
    official_links: [{ name: "少年JUMP官網", url: "https://www.shonenjump.com" }],
  },
  {
    id: "char-meruem",
    name: "梅路艾姆 (蟻王)",
    original_name: "メルエム (Meruem)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2003,
    avatar_url: "/images/idols/meruem.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-n5b7E2m8A24b.jpg",
    vote_count: 47900,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "梅路艾姆",
        gender: "male",
        birth_date: null,
        is_unrevealed: true,
        zodiac: "嵌合蟻頂點 ✦",
        avatar_url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=200",
      },
    ],
    notable_works: [
      { type: "傳世名局", title: "軍儀棋局之終章：小麥，你在那裡嗎？" },
    ],
    official_links: [{ name: "少年JUMP官網", url: "https://www.shonenjump.com" }],
  },
  {
    id: "char-hisoka",
    name: "西索",
    original_name: "ヒソカ＝モロウ (Hisoka Morow)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1998,
    avatar_url: "/images/idols/hisoka.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx11061-n5b7E2m8A24b.jpg",
    vote_count: 47500,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "西索",
        gender: "male",
        birth_date: "1976-06-06",
        is_unrevealed: false,
        zodiac: "雙子座 ♊︎",
        avatar_url: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=200",
      },
    ],
    notable_works: [
      { type: "念能力", title: "變化系：伸縮自如的愛 (Bungee Gum)" },
    ],
    official_links: [{ name: "少年JUMP官網", url: "https://www.shonenjump.com" }],
  },

  // ========================================================
  // 【遊戲王 Yu-Gi-Oh! - 純個人單人角色】
  // ========================================================
  {
    id: "char-yugi-atem",
    name: "闇遊戲 (亞圖姆)",
    original_name: "闇遊戯 (Yami Yugi)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1996,
    avatar_url: "/images/idols/yugi-atem.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx481-4J92m8B01aF7.png",
    wiki_slug: "Yugi_Mutou",
    vote_count: 53200,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "闇遊戲",
        gender: "male",
        birth_date: null,
        is_unrevealed: true,
        zodiac: "法老王 ✦",
        avatar_url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=200",
      },
    ],
    notable_works: [
      { type: "王牌", title: "黑魔導 / 歐西里斯的天空龍" },
      { type: "口號", title: "抽牌！(ドロー！)" },
    ],
    official_links: [{ name: "遊戲王官網", url: "https://www.yugioh-card.com" }],
    timeline: [
      { year: "三千年前", title: "古埃及無名法老王", desc: "以自身靈魂與七大千年神器封印大邪神佐克·內洛法。" },
      { year: "決鬥者王國", title: "戰勝帕卡斯奪回靈魂", desc: "以黑魔導與時間魔術師翻盤，奠定決鬥王傳奇起點。" },
      { year: "戰鬥城市篇", title: "集齊三幻神與宿命終局", desc: "迎戰海馬瀨人與闇馬利克，在冥界記憶石板前完成最後的儀式。" },
    ],
  },
  {
    id: "char-kaiba",
    name: "海馬瀨人",
    original_name: "海馬 瀬人 (Seto Kaiba)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1996,
    avatar_url: "/images/idols/kaiba.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx481-4J92m8B01aF7.png",
    wiki_slug: "Seto_Kaiba",
    vote_count: 52600,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "海馬瀨人",
        gender: "male",
        birth_date: "1980-10-25",
        is_unrevealed: false,
        zodiac: "天蠍座 ♏︎",
        avatar_url: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=200",
      },
    ],
    notable_works: [
      { type: "神卡", title: "青眼白龍 (Blue-Eyes White Dragon)" },
      { type: "名言", title: "強韌！無敵！最強！" },
    ],
    official_links: [{ name: "KONAMI 官網", url: "https://www.konami.com" }],
  },

  // ========================================================
  // 【吉伊卡哇 (ちいかわ) - 純個人單人角色】
  // ========================================================
  {
    id: "char-chiikawa",
    name: "吉伊卡哇",
    original_name: "ちいかわ (Chiikawa)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2020,
    avatar_url: "/images/idols/chiikawa.jpg",
    cover_url: "/images/idols/chiikawa.jpg",
    vote_count: 52100,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "吉伊卡哇",
        gender: "unrevealed",
        birth_date: "2017-05-01",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=200",
      },
    ],
    notable_works: [{ type: "特徵", title: "粉紅討伐棒 / 雖然膽小但絕不退縮" }],
    official_links: [{ name: "官方 X", url: "https://twitter.com/ngnchiikawa" }],
  },
  {
    id: "char-usagi",
    name: "兔兔 (烏薩奇)",
    original_name: "うさぎ (Usagi)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2019,
    avatar_url: "/images/idols/chiikawa.jpg",
    cover_url: "/images/idols/chiikawa.jpg",
    vote_count: 53900,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "兔兔",
        gender: "unrevealed",
        birth_date: "2019-01-22",
        is_unrevealed: false,
        zodiac: "水瓶座 ♒︎",
        avatar_url: "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=200",
      },
    ],
    notable_works: [
      { type: "奇行名言", title: "嗚啦 (ウラ)！呀哈 (ヤハ)！" },
      { type: "技能", title: "除草三級大師" },
    ],
    official_links: [{ name: "官方 X", url: "https://twitter.com/ngnchiikawa" }],
  },

  // ========================================================
  // 【鬼滅之刃 - 純個人單人角色】
  // ========================================================
  {
    id: "char-rengoku",
    name: "煉獄杏壽郎",
    original_name: "煉獄 杏寿郎 (Kyojuro Rengoku)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2016,
    avatar_url: "/images/idols/rengoku.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx112151-7knzP4A8u1hP.jpg",
    vote_count: 50400,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "煉獄杏壽郎",
        gender: "male",
        birth_date: "1895-05-10",
        is_unrevealed: false,
        zodiac: "金牛座 ♉︎",
        avatar_url: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=200",
      },
    ],
    notable_works: [
      { type: "奧義", title: "炎之呼吸 玖之型·煉獄" },
      { type: "名句", title: "燃燒你的心吧！(心を燃やせ)" },
    ],
    official_links: [{ name: "鬼滅官網", url: "https://kimetsu.com" }],
  },
  {
    id: "char-muzan",
    name: "鬼舞辻無慘",
    original_name: "鬼舞辻 無惨 (Muzan Kibutsuji)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 2016,
    avatar_url: "/images/idols/muzan.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-WBsBl0ClmgLd.jpg",
    vote_count: 45200,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "鬼舞辻無慘",
        gender: "unrevealed",
        birth_date: null,
        is_unrevealed: true,
        zodiac: "初代鬼始祖 ✦",
        avatar_url: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=200",
      },
    ],
    notable_works: [{ type: "宿敵地位", title: "十二鬼月統治者 / 青色彼岸花" }],
    official_links: [{ name: "鬼滅官網", url: "https://kimetsu.com" }],
  },

  // ========================================================
  // 【犬夜叉 - 純個人單人角色】
  // ========================================================
  {
    id: "char-sesshomaru",
    name: "殺生丸",
    original_name: "殺生丸 (Sesshomaru)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1996,
    avatar_url: "/images/idols/sesshomaru.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx249-1t9gK9hL0m5a.jpg",
    vote_count: 49100,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "殺生丸",
        gender: "male",
        birth_date: null,
        is_unrevealed: true,
        zodiac: "戰國貴公子大妖怪 ✦",
        avatar_url: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=200",
      },
    ],
    notable_works: [{ type: "名佩刀", title: "天生牙 / 爆碎牙" }],
    official_links: [
      { name: "高橋留美子官網", url: "https://www.sunday-webry.com" },
    ],
  },
  {
    id: "char-inuyasha-solo",
    name: "犬夜叉",
    original_name: "犬夜叉 (Inuyasha)",
    country: "JP",
    category: "character",
    entity_type: "solo",
    formation: "solo",
    debut_year: 1996,
    avatar_url: "/images/idols/inuyasha-solo.jpg",
    cover_url: "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx249-1t9gK9hL0m5a.jpg",
    vote_count: 48500,
    is_active: true,
    created_at: "2026-01-01T00:00:00Z",
    members: [
      {
        name: "犬夜叉",
        gender: "male",
        birth_date: null,
        is_unrevealed: true,
        zodiac: "半妖鐵碎牙 ✦",
        avatar_url: "https://images.unsplash.com/photo-1563089145-599997674d42?w=200",
      },
    ],
    notable_works: [{ type: "名奧義", title: "風之傷 / 爆流破 / 冥道殘月破" }],
    official_links: [
      { name: "高橋留美子官網", url: "https://www.sunday-webry.com" },
    ],
  },
];

// 相容性別名導出
export const MOCK_IDOLS: Idol[] = INITIAL_IDOLS;

export function getMockIdolById(id: string): Idol | undefined {
  return MOCK_IDOLS.find(
    (item) =>
      item.id === id ||
      item.name.toLowerCase() === decodeURIComponent(id).toLowerCase()
  );
}

export function getSoloIdolsByUniverse(universeId: string): Idol[] {
  return MOCK_IDOLS.filter(
    (item) => item.entity_type === "solo" && item.universe_id === universeId
  );
}

export function getUniverseById(universeId: string): Idol | undefined {
  return MOCK_IDOLS.find(
    (item) => item.entity_type === "universe" && item.id === universeId
  );
}


export const INITIAL_BATTLES: Battle[] = [
  {
    id: "battle-1",
    title: "2026 夏季跨界聲量巔峰賽",
    description: "全亞洲偶像強強對決！星街彗星與周杰倫兩大巨星聲量拉鋸，終局倒數中！",
    banner_url: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200",
    teaser_start_at: "2026-06-01T00:00:00Z",
    battle_start_at: "2026-06-15T00:00:00Z",
    battle_end_at: "2026-09-30T23:59:59Z",
    status: "live",
    champion_idol_id: null,
    created_at: "2026-06-01T00:00:00Z",
  },
  {
    id: "battle-2",
    title: "2026 春季次世代聲優與創作者新星盃",
    description: "花澤香菜領銜奪冠！回顧首季激戰與下剋上逆轉傳奇。",
    banner_url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200",
    teaser_start_at: "2026-03-01T00:00:00Z",
    battle_start_at: "2026-03-15T00:00:00Z",
    battle_end_at: "2026-05-31T23:59:59Z",
    status: "ended",
    champion_idol_id: "idol-5",
    created_at: "2026-03-01T00:00:00Z",
  },
];

export const INITIAL_COLLABS: Collab[] = [
  {
    id: "collab-1",
    idol_id: "idol-1",
    title: "星街彗星 台灣專場粉絲應援會願望池",
    status: "pledging",
    pledge_goal: 5000,
    pledge_count: 3840,
    event_date: "2026-11-20T19:00:00Z",
    event_venue: "Zepp New Taipei",
    banner_url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200",
    details_markdown: "集氣突破 5,000 票即解鎖台北巨型戶外應援看板，並啟動日本官方聯名周邊引進！",
    created_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "collab-2",
    idol_id: "idol-3",
    title: "NewJeans 快閃主題應援咖啡廳",
    status: "pledging",
    pledge_goal: 3000,
    pledge_count: 2450,
    event_date: "2026-10-15T14:00:00Z",
    event_venue: "台北中山區藝文空間",
    banner_url: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200",
    details_markdown: "為 Bunnies 打造專屬沉浸式打卡空間，集氣達標即釋出限量門票抽獎名額！",
    created_at: "2026-08-10T00:00:00Z",
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    idol_id: "idol-1",
    collab_id: "collab-1",
    source_type: "collab_exclusive",
    title: "【聯名限定】星街彗星 2026 璀璨彗星應援互動手燈",
    description: "內建 RGB 聲光同步晶片，支援現場舞台無線連動，粉絲專屬雷雕編號。",
    price: 980,
    stock: 120,
    min_votes_to_buy: 3,
    images: ["https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600"],
    is_active: true,
    created_at: "2026-08-15T00:00:00Z",
  },
  {
    id: "prod-2",
    idol_id: "idol-3",
    collab_id: "collab-2",
    source_type: "collab_exclusive",
    title: "【聯名限定】NewJeans Bunnies 復古卡帶藍牙音響組",
    description: "結合 Y2K 復古設計與高解析立體聲，隨附成員專屬寫真概念透卡一套。",
    price: 1880,
    stock: 45,
    min_votes_to_buy: 5,
    images: ["https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600"],
    is_active: true,
    created_at: "2026-08-18T00:00:00Z",
  },
  {
    id: "prod-3",
    idol_id: "idol-2",
    collab_id: null,
    source_type: "official_regular",
    title: "【官方周邊】周杰倫 嘉年華巡迴經典紀念連帽衫",
    description: "重磅純棉高質感刺繡，經典音符標誌低調奢華，百搭應援必備款。",
    price: 1580,
    stock: 80,
    min_votes_to_buy: 0,
    images: ["https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600"],
    is_active: true,
    created_at: "2026-08-01T00:00:00Z",
  },
  {
    id: "prod-4",
    idol_id: "idol-4",
    collab_id: null,
    source_type: "official_regular",
    title: "【官方周邊】Taylor Swift The Eras 典藏手繪吉他撥片組",
    description: "收錄各大時代巡演視覺圖案，精裝燙金鐵盒收藏組。",
    price: 650,
    stock: 150,
    min_votes_to_buy: 0,
    images: ["https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600"],
    is_active: true,
    created_at: "2026-08-01T00:00:00Z",
  },
];

export const INITIAL_MESSAGES: ContactMessage[] = [
  {
    id: "msg-1",
    sender_name: "陳小明",
    sender_email: "ming@example.com",
    category: "idol_nomination",
    subject: "推薦新偶像入駐：落日飛車",
    message: "希望平台能收錄台灣實力樂團落日飛車，讓更多全球粉絲看見台灣樂團的魅力！",
    status: "read",
    reply_content: "感謝您的建議！我們已將落日飛車列入審核名單，敬請期待下期提名投票！",
    replied_at: "2026-08-20T10:00:00Z",
    created_at: "2026-08-19T09:30:00Z",
  },
  {
    id: "msg-2",
    sender_name: "田中健一",
    sender_email: "tanaka@example.com",
    category: "collab_inquiry",
    subject: "星街彗星周邊聯名販售諮詢",
    message: "想確認聯名手燈的國際寄送地區是否包含日本地區呢？期待回覆！",
    status: "unread",
    reply_content: null,
    replied_at: null,
    created_at: "2026-08-25T14:15:00Z",
  },
];

export const INITIAL_ADMIN_PROFILE: Profile = {
  id: "admin-user-id",
  username: "UPAY 官方管理員",
  avatar_url: "/images/idols/admin-user-id.jpg",
  role: "admin",
  referral_code: "UPAY2026",
  bonus_votes: 999,
  created_at: "2026-01-01T00:00:00Z",
};

export const INITIAL_GUEST_PROFILE: Profile = {
  id: "guest-user-id",
  username: "熱血應援者",
  avatar_url: null,
  role: "user",
  referral_code: "OSHI8888",
  bonus_votes: 3,
  created_at: "2026-01-01T00:00:00Z",
};
